### ISSUE TITLE
Fast restart will cause data lost

### ISSUE THREAD

**Issue by chicknsoup** [buraksezer/olric#225] opened 2023-05-11 03:01 UTC
Hello there,
I'm doing some tests with Olric in embedded mode.
Two instances A and B are up and running with replicacount set to 2, ReadRepair set to true

Step 1: From A> put a key K --> K can be retrieved from both A and B
Step 2: Fast restart B (replica) --> K can still be retrieved from both A and B
Step 3: Fast restart A (owner of K) --> KEYNOTFOUND error occurs

If in Step 3 I wait for some time then it's working just fine.

It seems there is a race condition happening here.

**Comment by buraksezer** [comment] 2023-05-31 09:34
Hello, @chicknsoup I'm sorry for the late response. I'd like to see more logs here but it seems that this is not a bug. Olric doesn't have any mechanism to repair replicas actively. It only supports read-repair with `last-write-wins` policy. In addition to that, you are running nodes while the debug mode is enabled.

I'm closing this issue now. If you have any further questions, please don't hesitate to re-open this or create a new issue.

**Closed by buraksezer** 2023-05-31 09:34 UTC
Labels: question
